### PR TITLE
Update the compiled object files

### PR DESCRIPTION
**Pull request by Arkshine**
Used nasm 2.12.02rc9  with -O2. Tested fastly windows and linux and it seems okay.

### CODE REVIEW

**Comment by IgnacioFDM** [comment]
This makes me a bit nervous, because of
https://github.com/alliedmodders/amxmodx/blob/0bb5d86c20154bcd168d82f05588b3fcd8affea0/amxmodx/amxjitsn.asm#L9-15

They say to use 0.97.x or 0.98.x, and if 2.x must be used, *to use it with -O0*. Also is there a reason to use a release candidate version of nasm instead of the latest stable?

These assembly instructions were provided by TheDS in 2013 https://github.com/alliedmodders/amxmodx/commit/87d2a54638608f94a506f257eba463fd0be494b4

Maybe @dvander or @TheDS can provide extra info

**Comment by IgnacioFDM** [comment]
Here's the latest 0.98.x nasm version by the way in case you didn't find it in nasm home page

https://sourceforge.net/projects/nasm/files/Win32%20binaries/0.98.39/

**Comment by Arkshine** [comment]
I know, but "macho" is available only from 2.x. I think he said -O0 because I remember trying when he wrote that and it was not compiling unless you use -O0. 

But with the latest version it compiles fine and AMXX under linux/windows seems to run fine as well. 
I guess for extra safety I can compile win/lin with 0.98 and mac with latest and O0.

**Comment by IgnacioFDM** [comment]
Yes, I would suggest doing that. Win/Linux with 0.98 O2 and OS X with 2.x and O0.  It just makes me scared to have some small thing behave differently or corrupt memory causing some weird bug.

```-f macho``` is quite a funny command line argument

**Comment by Arkshine** [comment]
Just tried with 0.98.39 and -O2, but it gives me an error on linking. -O1 works, though.

With 0.98.22, it seems okay with -O2. What I used here.

**Comment by dvander** [comment]
IIRC it will crash if you don't use -O1.

**Comment by Arkshine** [comment]
Well, I've tried under windows/linux, and it was not crashing. But okay, let me recompile again with -O1. It won't hurt to care about safety.

**Pull request merged**
